### ISSUE TITLE
How to treeshake the components

### ISSUE THREAD

**Issue by SiNONiMiTY** [N00nDay/stwui#142]
Hi @N00nDay, greetings :)

This is an amazing project, I hope you can continue working on this.

A question, I am using the datepicker component and it is working really well. However, when I build the app, it seems that it packages all the components even though only the Datepicker is being used. Is there any workaround to treeshake the unused components?

Currently using SvelteKit and the 0.15 of STWUI.

**Comment by N00nDay** [comment]
Thanks for brining this up. My understanding was this was supposed to happen at compile time. Are you looking at a production build or are you looking while in development? 

If it is happening after build you could try importing like so:

import DatePicker from 'stwui/datepicker'

Please confirm it is not tree shaking after build first though as it should be. If not, and the above work around does not work I will have to setup individual exports for each component to make it happen.

**Comment by SiNONiMiTY** [comment]
I am doing a production build. 

Will try the suggested import approach and report back the findings.

Thank you :)

**Comment by N00nDay** [comment]
Yeah, this is what I feared. Each component will have to be added for export individually. I am currently still dialing in the DatePicker and have a little more time to get that polished off which has led me to add a more mobile-friendly version for All dropdown-type components (ie. Select, AutoComplete, Dropdown, etc.). After I get these completed I will start setting up tree shaking for each component.

**Comment by SiNONiMiTY** [comment]
Thank you for your hard work. Looking forward for that update. For the meantime, I can live with the unused modules being included packaged. Cheers 😁😁😁

**Comment by N00nDay** [comment]
@SiNONiMiTY The latest update (0.17.1-next) was mainly an error/warnings/dependency update but I did include individual exports. I have tested individual exports and they appear to be working with the following syntax `import DatePicker from 'stwui/date-picker'`. I am getting a `Cannot find module 'stwui/date-picker' or its corresponding type declarations.` warning but it appears to be working and when I run build I do not see any other components besides the ones I am including which leads me to believe tree shaking is in fact working with individual imports. Can you confirm this on your end? I will continue to work through the "Cannot find module..." warning in the meantime.

**Comment by SiNONiMiTY** [comment]
@N00nDay I will check and report the results here :)

**Comment by N00nDay** [comment]
Thanks for the comment, I already have the issue resolved I was just waiting to hear back from you on whether tree shaking was fixed before pushing the update. I should be able to push it tonight sometime and resolve exports entirely. Thanks for the assist!

**Comment by SiNONiMiTY** [comment]
Glad that I was able to help. Thanks for your hard work 🚀

**Comment by N00nDay** [comment]
The latest update is live and allows for individual components to be imported and tree shaking to happen. Documentation will be updated in the coming days.

**Comment by SiNONiMiTY** [comment]
Thanks @N00nDay, will be closing this issue.

**Comment by SiNONiMiTY** [comment]
oh, sorry for closing early 🙏

**Comment by bangdragon** [comment]
Hi i suggest use unocss with tailwind library for CSS. And we can insert icon using CSS class. And much more features.
