### ISSUE TITLE
Set modal size and position

### ISSUE THREAD

**Issue by bangdragon** [N00nDay/stwui#169]
I want to set modal size only 4/5 of screen and position at center of screen.
It seem this feature is mising

**Comment by N00nDay** [comment]
You should be able to do this by passing the desired classes or styles to the <Modal /> component.

**Comment by bangdragon** [comment]
I will try i

> You should be able to do this by passing the desired classes or styles to the component.

I will try it. Thanks

**Comment by N00nDay** [comment]
For reference, you can complete you objective with the following:

```
<Modal class="flex flex-col w-full items-center justify-center !p-0" ...>
  <Modal.Content slot="content" class="w-[80%]  max-w-full" ...>
    ...
  </Modal.Content>
</Modal>
```

**Comment by N00nDay** [comment]
@bangdragon were you able to solve this issue?

**Comment by N00nDay** [comment]
Closing this issue as I have confirmed this can be fixed by passing tailwind classes and creator is non-responsive.
