### ISSUE TITLE
Customizing DatePicker+Time button

### ISSUE THREAD

**Issue by MrWildanMD** [N00nDay/stwui#171]
How can i customizing the datepicker with time buttons? its conflicting with my custom css variable, thanks

**Comment by N00nDay** [comment]
This is currently not possible. The DatePicker is a fairly complex component so my initial goal was to get this out so people can start utilizing it and provide feedback. Enough time has passed that I can take this to the next stage and allow for customization. It will most likely require some extra boilerplate on the developer's end but I will see what I can come up with.

**Comment by MrWildanMD** [comment]
Alright, i understand, because after i seeing the source..then i decide to change my custom css class naming convention different from its datepicker button..so it didnt conflict

**Comment by N00nDay** [comment]
Something else I will be adding in the near future is class names for components to make this type thing easier even if the component is a wrapper the developer wouldn't have direct access to otherwise.

**Comment by MrWildanMD** [comment]
okay i have other question...for the Button component on form submit can i prevent page from reloading?
did event.preventDefault work?

**Comment by N00nDay** [comment]
Yes, you have to set the htmlType to button. I thought that was the default for button components but it appears that is not the case. I will add this to the docket.

**Comment by N00nDay** [comment]
@MrWildanMD I have added class identifiers to every component which should allow for deeper customization. I am still debating on pulling out the components to be passed in as slots for additional customization.

**Comment by MrWildanMD** [comment]
alright thank you, gotta check it later
