### ISSUE TITLE
Datepicker - Reset the bonded value not resetting the date label

### ISSUE THREAD

**Issue by neospirit** [N00nDay/stwui#182]
### Current Behavior

When resetting the bonded value of a date picker, the label displaying the date is not reset.

Here's a small SvelteKit project that shows the issue: https://github.com/neospirit/test-stwui-datepicker

### Expected Behavior

When resetting the bonded value from an external event for instance, the date picker should reset its label

### Steps To Reproduce

Use this project: https://github.com/neospirit/test-stwui-datepicker 

1. Click on the RESET button
2. The date picker does not update its label but the startDate value is set to null

### Link to Reproduction / Stackblitz

https://github.com/neospirit/test-stwui-datepicker

**Comment by neospirit** [comment]
Hi @N00nDay, I have updated to the latest version and it seems that when a date picker has the `showTime` option, when you select a date, it shows "undefined NaN" when picking up a time.

**Comment by N00nDay** [comment]
Please provide a reproduction. The docs are not showing the behavior you are explaining.
