### ISSUE TITLE
Trying to get stwui to work and missing styling

### ISSUE THREAD

**Issue by KevM** [N00nDay/stwui#21]
When I try out this component library. I wanted to visualize my profile after I got google auth working. So I used a Chip. I see tailwind styles being applied to other markup. I'm likely doing something basic/wrong as I have been away from the front end for a looong time.

``` js 

<script lang="ts">
   // ...
    import { Chip } from 'stwui';
  // ...
</script>

{#if $page.data.session.user}
    <Chip size="lg">
        <Chip.Avatar slot="avatar" src="{$page.data.session.user.user_metadata.avatar_url}"/>
        <Chip.Label slot="label">{$page.data.session.user.user_metadata.full_name}</Chip.Label>
    </Chip>
{/if}
```

I see mark up being emitted but it is not styled:
![image](https://user-images.githubusercontent.com/1565/194916145-56abf546-5809-4fed-966d-b6d3b7c53249.png)

I expected it to look this (but with a dude not as good looking): 
![image](https://user-images.githubusercontent.com/1565/194916522-026a922c-d98c-4ef3-8e8e-53162d6fdda4.png)

tailwind.config.cjs
``` js
module.exports = {
  content: 
  [
    './src/**/*.{html,js,svelte,ts}',
    '../node_modules/stwui/**/*.{svelte,js,ts,html}'
  ],
  theme: {
    extend: {},
  },
  plugins: [
    require('@tailwindcss/forms'),
		require('stwui/plugin')
  ],
  darkMode: 'class'
}
```

app.css
``` css
@tailwind base;
@tailwind components;
@tailwind utilities;
```

+layout.svelte
``` svelte
<script lang="ts">
  // importing app css in the layout
  import "../app.css";
  // ...
</script>
```

**Comment by N00nDay** [comment]
Are you working with sveltekit or a svelte app. At first glance, it looks like the content section in your tailwind.config is wired up. You have:
```
content: 
  [
    './src/**/*.{html,js,svelte,ts}',
    '../node_modules/stwui/**/*.{svelte,js,ts,html}'
  ],
```
but typically the node_modules folder is at the root so you should have
```
content: 
  [
    './src/**/*.{html,js,svelte,ts}',
    './node_modules/stwui/**/*.{svelte,js,ts,html}'
  ],
```

Basically, remove a period before node_modules. 

Let me know if this solves your issue or not. I have a test server that I just dumped your code into and everything appears to be working as expected.

**Comment by KevM** [comment]
Hmm. I am running SvelteKit. I fixed the config to remove the extra `.` that was my mistake. I misread the folder structure. Once I restarted the dev server the styling is working. Thanks for your sanity check. I was close but messed up your instructions.

**Comment by N00nDay** [comment]
No worries, glad we got it figured out! We are still in beta so there was a good chance I had missed something as well. Thanks for using the package and providing feedback!
