### ISSUE TITLE
DatePicker can not switch to next/prev month/year if already has value

### ISSUE THREAD

**Issue by rey5137** [N00nDay/stwui#214]
### Current Behavior

When DatePicker has value, and you want to switch to next/prev month/year in dropdown, The UI is animated but the current month stayed the same as current value.

### Expected Behavior

The current month should be switched to  next/prev month/year

### Steps To Reproduce

1. Choose a value for DatePicker
2. Click DatePicker again to open dropdown
3. Click Next/Prev month/year button

**Comment by denuser** [comment]
Fixed in 0.21.2-next, could you check it?

**Comment by rey5137** [comment]
I confirmed this is fixed in 0.21.2-next. Thanks
