### ISSUE TITLE
Allow for more customization with Dropdown Items

### ISSUE THREAD

**Issue by KevM** [N00nDay/stwui#31]
``` html
<Dropdown.Items slot="items">
    <Dropdown.Items.Item>
        <Button>
            <a href="/auth/profile">Profile</a>
            <Button.Trailing slot="trailing">
                <Button.Icon slot = "icon" icon="account_circle" />
            </Button.Trailing>
        </Button>   
    </Dropdown.Items.Item>
    <Dropdown.Items.Item>
        <a href="/auth/logout">Sign Out <Icon icon="logout"/></a>
    </Dropdown.Items.Item>
</Dropdown.Items>
```

First item hover has nested styling for hover: 
![image](https://user-images.githubusercontent.com/1565/195878634-c8ba84f1-7336-4542-b26a-16eb57b53d1f.png)
Second item hover looks correct but is missing the nice alignment of the `Button`: 
![image](https://user-images.githubusercontent.com/1565/195878730-6a616479-8b7c-4eeb-a649-68618a3cf357.png)

**Comment by N00nDay** [comment]
The Button component was not designed to be inside a Dropdown. I think a better solution might be allowing an icon to be right-aligned to the end of the Dropdown Item instead of the left. Does this fit your use case @KevM ?

**Comment by KevM** [comment]
I think that would solve my use case.

**Comment by N00nDay** [comment]
This will be solved in the next update. You can check out the notes in the [Breaking Changes Announcement](https://github.com/N00nDay/stwui/discussions/46). Below is an image to show you what you will be able to do.

<img width="278" alt="Screen Shot 2022-10-21 at 12 57 16 PM" src="https://user-images.githubusercontent.com/28783829/197249233-27624c21-e9b0-4ba2-b01b-feb8a7c231ba.png">
