### ISSUE TITLE
Error when Building: EISDIR: illegal operation on a directory, read

### ISSUE THREAD

**Issue by DomenicWalther** [N00nDay/stwui#64]
When trying to build a Svelte-Kit App with stwui Components I get the error:

```
[vite:load-fallback] Could not load /Users/domenicwalther/Documents/Programming/test-app/node_modules/stwui (imported by src/routes/+page.svelte): EISDIR: illegal operation on a directory, read
error during build:
Error: Could not load /Users/domenicwalther/Documents/Programming/test-app/node_modules/stwui (imported by src/routes/+page.svelte): EISDIR: illegal operation on a directory, read
```

Can be reproduced by just following stwui Docs for installing and adding a component somewhere and then running npm run build.

**Comment by N00nDay** [comment]
The issue has to do with using svelte/kit specific functionality in the package (ie. browser, page, etc.)

I have tracked down the issues down to three components:
- **DatePicker** - uses browser
- **Pagination** - use page
- **Table** - uses page

The `DatePicker` is salvageable with some minor tweaks but `Pagination` and `Table` will be lost in the process until I have more time to bring them back.

**Comment by N00nDay** [comment]
I was able to salvage the `Pagination` and `Table` components but they have been changed significantly. Basically, all the automatic search parameters are now on the user to implement as the package cannot access that functionality from svelte/kit as a package.

**Comment by tylerjgarland** [comment]
@N00nDay , is there any hacks we can do to temporarily fix builds? I only use the minimal table implementation. Readonly columns and headers. If not, all good. Thanks!

**Comment by N00nDay** [comment]
I take it back. Figured out what the issue is and it is now resolved. Builds will work with 0.0.31.
