### ISSUE TITLE
Pagination showing wrong number of pages in table

### ISSUE THREAD

**Issue by danielpinto8zz6** [N00nDay/stwui#67]
Hi, 

When using pagination in the table component, it is showing less 1 page number than supposed, see attached image

<img width="1122" alt="image" src="https://user-images.githubusercontent.com/8846362/202921228-508fd550-8e53-4a31-a55f-977703191a7b.png">

**Comment by N00nDay** [comment]
What version are you using?

**Comment by N00nDay** [comment]
I think I see what the problem is. Page sizes are hardcoded to 25 from a previous version. I will change to so you can set the page size yourself.
