### ISSUE TITLE
Handle named form actions using Button component

### ISSUE THREAD

**Issue by dominic-schmid** [N00nDay/stwui#83]
I'm sorry if this is a trivial thing but I'm new to SvelteKit and can't figure out how to use named server-side form actions specified in `+page.server.ts` with Buttons from stwui.

I couldn't find anything about forms in the STWUI docs either. Is this not yet supported?

As per the [official SvelteKit documentation](https://kit.svelte.dev/docs/form-actions), you can create a form and

- specify the `formaction` for each button
- leave the `formaction` blank and use the specified form  `action`
- leave the `formaction` blank and use the default form action

to have the submission handled by the server.

### +page.server.ts
```ts
 export const actions: Actions = {
	login: async ({cookies, request}) => {
		const data = await request.formData();
		const email = data.get("email");
		const password = data.get("password");
		console.log(`LOGIN: email: ${email}\npassword: ${password}`);
		return {success: true};
	},
	register: async ({cookies, request}) => {
		const data = await request.formData();
		const email = data.get("email");
		const password = data.get("password");
		console.log(`REGISTER: email: ${email}\npassword: ${password}`);
		return {success: true};
	}
};
```

## Vanilla Sveltekit: +page.svelte

As an example, each button calls a different action.

```html
<form method="POST" action="?/login" use:enhance>
    <button type="submit">Login</button>
    <button type="submit" formaction="?/register">Register</button>
</form>
```

## STWUI: +page.svelte

Using the `Button` for the form/default action works fine, but what if I want to use named actions? Where can I do this?

```html
<form method="POST" use:enhance>
    <Button type="primary" htmlType="submit">Login</Button>
    <Button type="link">Register</Button>
</form>
```

**Comment by N00nDay** [comment]
Have you tried adding formaction to the Button component? All actions should be forwarded to the component automatically.

**Comment by dominic-schmid** [comment]
Well that was an easy fix, sorry 😄 

Interesting, so components take in any props, even when they aren't directly exported. That's awesome!

**Comment by N00nDay** [comment]
> Well that was an easy fix, sorry 😄 
> 
> 
> 
> Interesting, so components take in any props, even when they aren't directly exported. That's awesome!  

Yeah, I can work on documenting this in the future as it shouldn't be let to assumption.
